---
version: '3.1'

##  Component:  PoC Nifi Ejemplo: Twitter-Kafka-MongoDB
##  Version:    0.2
##  Author:     Versia Tecnologías Emergentes
##

networks:
  labnet:
    driver: bridge

services:

  mongo:
    image: mongo
    container_name: Poc_nifi_mongodb
    restart: always
    ports:
        - "27017:27017"
      #environment:
        #MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD:
    networks:
        - labnet
  
  mongo-express:
    image: mongo-express
    container_name: Poc_nifi_mongo_express
    restart: always
    ports: 
        - "8081:8081"
    environment:
        #ME_CONFIG_MONGODB_ADMINUSERNAME: root
        #ME_CINFIG_MONGODB_ADMINPASSWORD:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
        - labnet
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: Poc_nifi_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
        - labnet
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: Poc_nifi_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
        - labnet

  nifi:
    image: apache/nifi
    container_name: Poc_nifi_nifi
    ports:
        - "8080:8080"
    environment: 
        - NIFI_WEB_HTTP_PORT=8080
    networks:
        - labnet
  