---
version: '3.1'

##  Component:  Mongodb and MongoExpress
##  Version:    0.1
##  Author:     Versia Tecnologías Emergentes
##

networks:
  labnet:

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
         - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: Versia18
    networks:
      - labnet
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Versia18
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Versia18
    depends_on:
      - mongo
    networks:
      - labnet