---
version: '3.1'

##  Component:  nifi
##  Version:    0.2
##  Author:     Versia Tecnologías Emergentes
##

networks:
  labnet:

services:

  nifi:
    image: apache/nifi
    container_name: Poc_nifi_nifi
    ports:
        - "8080:8080"
    environment:
        - NIFI_WEB_HTTP_PORT=8080
    networks:
        - labnet